package main

import (
	"fmt"
	"os"
	"github.com/hedgeg0d/groq"
)

func main() {
	client := &groq.GroqClient{ApiKey: os.Getenv("GROQ_API_KEY")}
	params := groq.SpeechParameters{
        Voice:          "Fritz-PlayAI",
        ResponseFormat: "wav",
    }
    audio, err := client.CreateSpeech("Hello! This is an example voiceline generated by AI.", params)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		return
	}
	os.WriteFile("speech.wav", audio, 0644)
}
